### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [takagi/marching-cubes#1]
Please consider adding :description, :author and :license information to your ASDF system(s). This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by takagi** [comment]
Dene in 2abb701d307f4779e6f98f3c95950d6eafe1d224.
